services:
  odoo:
    build: odoo
    depends_on:
      - db
      - elastic
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf
      - odoo-web-data:/var/lib/odoo
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
  shopinvader:
    build: shopinvader
    ports:
      - "3000:3000"
    depends_on:
      - odoo
      - elastic
    environment:
      - SASS_NO_DEPRECATION_WARNINGS=1
      - NUXT_PUBLIC_SHOPINVADER_ERP_URL=http://odoo:8069/shopinvader_demo
      - NUXT_PUBLIC_SHOPINVADER_ELASTICSEARCH_URL=http://localhost:9200
      - NUXT_PUBLIC_SHOPINVADER_ELASTICSEARCH_INDICES_PRODUCTS=demo_elasticsearch_backend_product_variant
      - NUXT_PUBLIC_SHOPINVADER_ELASTICSEARCH_INDICES_CATEGORIES=demo_elasticsearch_backend_product_category
    volumes:
      - ./shopinvader/template:/app/template
      - /app/template/node_modules
  elastic:
    image: elasticsearch:7.17.10
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=admin
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.authc.accept_default_password=true
      - xpack.security.authc.anonymous.username=anonymous
      - xpack.security.authc.anonymous.roles=anonymous_role
      - xpack.security.authc.anonymous.authz_exception=false
      # CORS settings
      - http.cors.enabled=true
      - "http.cors.allow-origin=*"  # Allow all origins
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - "http.cors.allow-headers=Authorization,X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Accept"
      - http.cors.allow-credentials=true
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
volumes:
  odoo-web-data:
  odoo-db-data:
  elasticsearch_data:
  mongodb:
